import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const codeNext = localFont({
  variable: "--font-code-next",
  src: [
    {
      path: "./font/code-next/CodeNext-Trial-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/code-next/CodeNext-Trial-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./font/code-next/CodeNext-Trial-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});
const poppins = localFont({
  variable: "--font-poppins",
  src: [
    {
      path: "./font/poppins/Poppins-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/poppins/Poppins-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./font/poppins/Poppins-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "./font/poppins/Poppins-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${codeNext.className}`}>
      <body className={`${poppins.className}`}>{children}</body>
    </html>
  );
}
